apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
data:
  application.yml: |-
    targets:
      admin:
        uaa: https://uaa.cf4k8s.wrightcode.io
    uaa:
      identity-zone-id: uaa
    scopes:
      trade: trade
      account: account
      portfolio: portfolio
      bank: tanzu.bank
    logging:
      level:
        root: DEBUG
        org.apache.http: DEBUG
        org.springframework.security.oauth2: DEBUG
        org.springframework.web.client.RestTemplate: DEBUG
    security:
      oauth2:
        client:
          uaa:
            clientId: tanzu_zoneadmin
            clientSecret: tanzu
            accessTokenUri: http://uaa.cf4k8s.wrightcode.io/login/oauth/access_token
            access-token-uri: http://uaa.cf4k8s.wrightcode.io/login/oauth/access_token
            userAuthorizationUri: http://uaa.cf4k8s.wrightcode.io/login/oauth/authorize
